#!/usr/bin/env python3
"""
AutoGen Agent: marketign
Generated by AI Factory
Provider: Groq (Llama 3) | Model: llama-3.3-70b-versatile

Usage:
  1. pip install pyautogen google-generativeai google-cloud-aiplatform
  2. Set your API key as an environment variable
  3. Run: python marketign_agent.py
"""
import os
import autogen

# ── LLM Configuration ─────────────────────────────────────────────────
# Replace with your own API key or set via environment variable
API_KEY = os.getenv("AGENT_API_KEY", "")

llm_config = {
    "config_list": [{
        "model": "llama-3.3-70b-versatile",
        "api_key": API_KEY,

        "base_url": "https://api.groq.com/openai/v1",
    }],
    "cache_seed": None,  # Disable caching for fresh responses
}

# ── Agent Definition ───────────────────────────────────────────────────
assistant = autogen.AssistantAgent(
    name="marketign",
    system_message="""[Business Context: arco is in the ece vertical, generating 10k_50k targeting: e.]  gin customer""",
    llm_config=llm_config,
)

user_proxy = autogen.UserProxyAgent(
    name="customer",
    human_input_mode="ALWAYS",
    max_consecutive_auto_reply=10,
    code_execution_config=False,
)

# ── Run ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print(f"\n============================================================")
    print(f"  AI Factory Agent: marketign")
    print(f"  Model: llama-3.3-70b-versatile via Groq (Llama 3)")
    print(f"============================================================\n")
    print("Type your messages below. Type 'exit' to quit.\n")
    user_proxy.initiate_chat(assistant, message="Hello! How can I help you today?")
